/**
 * Generates public/sitemap.xml from the real route table.
 *
 * The hand-maintained sitemap had drifted: it advertised /pricing (a commented-out route)
 * and /platform (never a route), and omitted /blog, /how-we-help/*, every module page and
 * every blog post. Generating it from the same list the router uses removes the drift.
 *
 * `lastmod` comes from the last git commit that touched each page's source, so it is real
 * rather than a frozen date. Falls back to the build date outside a git checkout.
 *
 * Run via `npm run sitemap` (also wired to prebuild).
 */
import { writeFileSync, readdirSync, readFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SITE_URL = (process.env.VITE_SITE_URL ?? "https://zedops.com").replace(/\/+$/, "");
const BLOG_DIR = path.join(root, "src/content/blog");

/** Module pages live in data, not as files - read the ids straight out. */
function moduleIds() {
  const file = path.join(root, "src/data/platformFeatures.ts");
  const src = readFileSyncSafe(file);
  return [...src.matchAll(/^\s*id:\s*"([^"]+)"/gm)].map((m) => m[1]);
}

function readFileSyncSafe(p) {
  try {
    return readFileSync(p, "utf8");
  } catch {
    return "";
  }
}

function blogSlugs() {
  try {
    return readdirSync(BLOG_DIR)
      .filter((f) => f.endsWith(".md"))
      .map((f) => f.replace(/\.md$/, ""));
  } catch {
    return [];
  }
}

/** Last commit date (YYYY-MM-DD) for a path, or null outside git. */
function lastmod(relPath) {
  try {
    const out = execFileSync("git", ["log", "-1", "--format=%as", "--", relPath], {
      cwd: root,
      stdio: ["ignore", "pipe", "ignore"],
    })
      .toString()
      .trim();
    return out || null;
  } catch {
    return null;
  }
}

const fallback = new Date().toISOString().slice(0, 10);

/** path, priority, changefreq, source file(s) used to derive lastmod */
const entries = [
  ["/", 1.0, "weekly", "src/pages/Home.tsx"],
  ["/solutions", 0.85, "monthly", "src/pages/SolutionsPage.tsx"],
  ["/zed-ai", 0.85, "monthly", "src/pages/ZedAIPage.tsx"],
  ["/how-we-help", 0.8, "monthly", "src/pages/HowWeHelpHubPage.tsx"],
  ["/how-we-help/project-stage", 0.7, "monthly", "src/pages/ProjectLifecyclePage.tsx"],
  ["/how-we-help/company", 0.7, "monthly", "src/pages/HowWeHelpCompanyPage.tsx"],
  ["/how-we-help/team", 0.7, "monthly", "src/pages/HowWeHelpTeamPage.tsx"],
  ["/how-we-help/role", 0.7, "monthly", "src/pages/HowWeHelpRolePage.tsx"],
  ["/who-we-serve", 0.8, "monthly", "src/pages/WhoWeServePage.tsx"],
  ["/who-we-serve/general-contractors", 0.7, "monthly", "src/pages/personas/GCPage.tsx"],
  ["/who-we-serve/owners", 0.7, "monthly", "src/pages/personas/OwnersPage.tsx"],
  ["/who-we-serve/project-managers", 0.7, "monthly", "src/pages/personas/PMPage.tsx"],
  ["/who-we-serve/consultants", 0.7, "monthly", "src/pages/personas/ConsultantsPage.tsx"],
  ["/security", 0.7, "monthly", "src/pages/SecurityPage.tsx"],
  ["/roadmap", 0.7, "weekly", "src/pages/RoadmapPage.tsx"],
  ["/about", 0.6, "monthly", "src/pages/AboutPage.tsx"],
  ["/blog", 0.8, "weekly", "src/pages/BlogIndexPage.tsx"],
  ["/early-access", 0.9, "monthly", "src/pages/EarlyAccessPage.tsx"],
  ["/contact", 0.7, "monthly", "src/pages/ContactPage.tsx"],
  ["/privacy", 0.2, "yearly", "src/pages/PrivacyPage.tsx"],
  ["/terms", 0.2, "yearly", "src/pages/TermsPage.tsx"],
];

for (const id of moduleIds()) {
  entries.push([`/platform/module/${id}`, 0.8, "monthly", "src/data/platformFeatures.ts"]);
}
for (const slug of blogSlugs()) {
  entries.push([`/blog/${slug}`, 0.6, "monthly", `src/content/blog/${slug}.md`]);
}

const esc = (s) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

const urls = entries
  .map(([route, priority, freq, src]) => {
    const lm = lastmod(src) ?? fallback;
    return [
      "  <url>",
      `    <loc>${esc(SITE_URL + route)}</loc>`,
      `    <lastmod>${lm}</lastmod>`,
      `    <changefreq>${freq}</changefreq>`,
      `    <priority>${priority.toFixed(1)}</priority>`,
      "  </url>",
    ].join("\n");
  })
  .join("\n");

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs - do not edit by hand. Run: npm run sitemap -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;

writeFileSync(path.join(root, "public/sitemap.xml"), xml);
console.log(`sitemap.xml: ${entries.length} URLs`);
