/**
 * Generates public/sitemap.xml from the shared route table in scripts/lib/routes.mjs
 * - the same list `prerender.mjs` uses, so the sitemap and the prerendered HTML
 * cannot disagree with each other.
 *
 * The previous hand-maintained file had drifted badly: it advertised /pricing (a
 * commented-out route) and /platform (never a route), and omitted /blog, all four
 * /how-we-help pages, every module page and every blog post.
 *
 * `lastmod` comes from the last git commit that touched each page's source, so it
 * reflects real edits. When git history is unavailable it falls back to the build
 * date and says so.
 *
 * Run via `npm run sitemap` (wired to prebuild).
 */
import { writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import path from "node:path";
import { ROOT, pageUrl, routes } from "./lib/routes.mjs";

/** Last commit date (YYYY-MM-DD) for a path, or null outside git. */
function lastmod(relPath) {
  try {
    return (
      execFileSync("git", ["log", "-1", "--format=%as", "--", relPath], {
        cwd: ROOT,
        stdio: ["ignore", "pipe", "ignore"],
      })
        .toString()
        .trim() || null
    );
  } catch {
    return null;
  }
}

let gitAvailable = true;
try {
  execFileSync("git", ["rev-parse", "--is-inside-work-tree"], {
    cwd: ROOT,
    stdio: ["ignore", "ignore", "ignore"],
  });
} catch {
  gitAvailable = false;
}
if (!gitAvailable) {
  console.log("  note: no git history available, lastmod falls back to the build date");
}

const fallback = new Date().toISOString().slice(0, 10);
const esc = (s) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

const urls = routes()
  .map((r) => {
    const loc = pageUrl(r.path);
    return [
      "  <url>",
      `    <loc>${esc(loc)}</loc>`,
      `    <lastmod>${lastmod(r.source) ?? fallback}</lastmod>`,
      `    <changefreq>${r.changefreq}</changefreq>`,
      `    <priority>${r.priority.toFixed(2)}</priority>`,
      "  </url>",
    ].join("\n");
  })
  .join("\n");

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs - do not edit by hand. Run: npm run sitemap -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;

writeFileSync(path.join(ROOT, "public/sitemap.xml"), xml);
console.log(`sitemap.xml: ${routes().length} URLs`);
