/**
 * Generates public/sitemap.xml from the shared route table in scripts/lib/routes.mjs
 * - the same list `prerender.mjs` uses, so the sitemap and the prerendered HTML
 * cannot disagree with each other.
 *
 * The previous hand-maintained file had drifted badly: it advertised /pricing (a
 * commented-out route) and /platform (never a route), and omitted /blog, all four
 * /how-we-help pages, every module page and every blog post.
 *
 * `lastmod` is the blog post's frontmatter date (or `updated`) when a route has one,
 * otherwise the last git commit that touched the route's source file, so it reflects
 * real edits. When neither is available it falls back to the build date.
 *
 * Run via `npm run sitemap` (wired to prebuild).
 */
import { writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import path from "node:path";
import { ROOT, hasAlternates, indexedLangsOf, localePath, pageUrl, routes } from "./lib/routes.mjs";

/** Last commit date (YYYY-MM-DD) for a path, or null outside git. */
function lastmod(relPath) {
  try {
    return (
      execFileSync("git", ["log", "-1", "--format=%as", "--", relPath], {
        cwd: ROOT,
        stdio: ["ignore", "pipe", "ignore"],
      })
        .toString()
        .trim() || null
    );
  } catch {
    return null;
  }
}

let gitAvailable = true;
try {
  execFileSync("git", ["rev-parse", "--is-inside-work-tree"], {
    cwd: ROOT,
    stdio: ["ignore", "ignore", "ignore"],
  });
} catch {
  gitAvailable = false;
}
if (!gitAvailable) {
  console.log("  note: no git history available, lastmod falls back to the build date");
}

const fallback = new Date().toISOString().slice(0, 10);
const esc = (s) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

// One <url> per route per language, each listing every alternate (itself included) plus
// x-default -> English. Only indexed languages (src/config/seoLangs.json) are listed; a route with
// fewer than two indexed versions has no alternates.
const all = routes();
const urls = all
  .flatMap((r) =>
    indexedLangsOf(r).map((lang) => {
      const alternates =
        hasAlternates(r)
          ? [
              ...indexedLangsOf(r).map((l) => ["" + l, pageUrl(localePath(r.path, l))]),
              ["x-default", pageUrl(r.path)],
            ].map(([hl, href]) => `    <xhtml:link rel="alternate" hreflang="${hl}" href="${esc(href)}" />`)
          : [];
      return [
        "  <url>",
        `    <loc>${esc(pageUrl(localePath(r.path, lang)))}</loc>`,
        `    <lastmod>${r.lastmod || lastmod(r.source) || fallback}</lastmod>`,
        `    <changefreq>${r.changefreq}</changefreq>`,
        `    <priority>${r.priority.toFixed(2)}</priority>`,
        ...alternates,
        "  </url>",
      ].join("\n");
    }),
  )
  .join("\n");
const urlCount = all.reduce((n, r) => n + indexedLangsOf(r).length, 0);

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs - do not edit by hand. Run: npm run sitemap -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
${urls}
</urlset>
`;

writeFileSync(path.join(ROOT, "public/sitemap.xml"), xml);
console.log(`sitemap.xml: ${urlCount} URLs (${all.length} routes)`);
